package com.yatatsu.fieldschema.processor;

import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.TypeSpec;
import java.io.IOException;
import java.util.stream.Stream;
import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;

public class FieldSchemaCodeWriter {

  private static final String TARGET_PACKAGE_NAME = "com.yatatsu.fieldschema";
  private static final String TARGET_CLASS_NAME = "FS";
  private final Stream<FieldSchemaClassHolder> fieldSchemaClassHolders;

  FieldSchemaCodeWriter(Stream<FieldSchemaClassHolder> fieldSchemaClassHolders) {
    this.fieldSchemaClassHolders = fieldSchemaClassHolders;
  }

  public void write(Filer filer) throws IOException {
    TypeSpec.Builder typeSpecBuilder =
        TypeSpec.classBuilder(TARGET_CLASS_NAME).addModifiers(Modifier.PUBLIC, Modifier.FINAL);
    typeSpecBuilder.addJavadoc(
        "FieldSchema\n\n" + "This is auto generated by FieldSchema. Do not modify.\n");
    fieldSchemaClassHolders.map(FieldSchemaCodeWriter::createInnerTypeSpec)
        .forEach(typeSpecBuilder::addType);
    JavaFile.builder(TARGET_PACKAGE_NAME, typeSpecBuilder.build()).build().writeTo(filer);
  }

  private static TypeSpec createInnerTypeSpec(FieldSchemaClassHolder holder) {
    TypeSpec.Builder builder = TypeSpec.classBuilder(holder.getSimpleClassName().toLowerCase())
        .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL);
    holder.getFieldNames()
        .map(fieldName -> FieldSpec.builder(String.class, fieldName, Modifier.PUBLIC,
            Modifier.STATIC, Modifier.FINAL).initializer("$S", fieldName).build())
        .forEach(builder::addField);
    return builder.build();
  }
}
